1 new caller workflow templates
graasp/.github pull request #2
Opened 2022-08-22 09:39 UTC by victorggonzalez

added the caller workflow templates from graasp deploy, so they can be accessed directly from the Actions tab of any repository

2022-08-29 09:18 UTC, pyphilia requested changes
Looks good, but most of them are copy pasted from graasp-deploy, aren't they? Isn't there a possibility to have them sync? Or move everything to `.github`? Because now it means if we want to add an env variable (in app) we need to change all the app workflows, the deploy's ones and these ones so it's sync. I guess we should discuss.

2022-08-29 09:18 UTC, pyphilia commented on workflow-templates/cdelivery-s3-apps-caller.properties.json
> +  "description": "Build, test and push a package to Amazon S3 and deploy to CloudFront staging environment.",
```suggestion
"description": "Build, test and push an app to Amazon S3 and deploy to CloudFront staging environment.",
```

2022-08-29 09:18 UTC, pyphilia commented on workflow-templates/cdeployment-s3-apps-caller.properties.json
> +  "description": "Build, test and push a package to Amazon S3 and deploy to CloudFront production environment.",
```suggestion
"description": "Build, test and push an app to Amazon S3 and deploy to CloudFront production environment.",
```

2022-08-29 09:18 UTC, pyphilia commented on workflow-templates/cintegration-s3-caller.yml
> +      show-notifications:
Can we sort them?

2022-08-29 15:48 UTC, victorggonzalez commented on workflow-templates/cintegration-s3-caller.yml
> +      show-notifications:
done!

2022-08-29 15:50 UTC, victorggonzalez commented
Included changes after review. 

As we talked about, the idea is to remove the templates from graasp-deploy and include them here. That way it's easy to add the workflows directly from the workflows tab.
Now if we want to add an env variable we only need to change these.

2022-09-01 08:25 UTC, pyphilia approved these changes

2022-09-03 22:04 UTC, merged